name: Pocco_Restrict

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [labeled, synchronize, opened, ready_for_review]

cconcurrency:
  group: >
    ci-${{ github.event_name }}-
    ${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    # 実行条件まとめ
    if: >
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '@ci-run')
      ) ||
      (
        github.event_name == 'pull_request' &&
        !github.event.pull_request.draft &&
        contains(github.event.pull_request.labels.*.name, 'ci-run')
      )

    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Setup Node (example)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

        #初回テスト時プルリクエストする際に　@ci-run とコメント。